spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:56982/railway
    username: root
    password: bsIrKNiPrQCOVGnVwwDNKqcfgeFzhvqA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false

#Open api configuration
open_api:
  title: PRUEBA TECNICA CINE PLANET
  description: API de Gestion de Pedidos, Productos, Autenticacion y Autorizacion mediante JWT
  contact:
    name: Jesus Cangalaya
    email: jesuscangalaya1@gmail.com
  servers:
    local:
      url: http://render:8080
      description: Deploy in Render
    production:
      url: https://miempresa.comm
      description: Productive Environment

#security
jwt:
  expiration: 36000
  secret: secretsecretsecretsecretsecretsecretsecretsecret

